#!/usr/bin/env python3
import click
import json
import logging
import os
import subprocess

logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
log = logging.getLogger(__name__)

@click.command('vm-import-vol')
@click.option('--pool', type=str, default='default')
@click.argument('name', type=str)
@click.argument('path', type=str)
def imp(name, path, pool):
    if not os.path.exists(path):
        log.error(f"{path} does not exist")
        exit(1)

    info = json.loads(subprocess.check_output(["qemu-img", "info", "--output=json", path]))
    fmt = info["format"]
    if fmt == "raw":
        size = os.stat(path).st_size
        log.info(f"{path} is {size} bytes")
    else:
        size = int(info["virtual-size"])

    log.info(f'importing {path} (format {fmt}, size {size}) to pool "{pool}" as "{name}"')
    subprocess.check_call(["virsh", "vol-create-as", pool, name, str(size), "--format", fmt])
    args = ["virsh", "vol-upload", "--pool", pool, name, path]
    if fmt == "qcow2":
        args.append("--sparse")

    log.info(f'importing with command {args}')
    subprocess.check_call(args)

if __name__ == "__main__":
    imp()
