#!/usr/bin/env python3
import click
import json
import logging
import os
import subprocess

logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
log = logging.getLogger(__name__)


@click.command("vm-thin-clone-vol")
@click.option("--pool", type=str, default="default")
@click.argument("name", type=str)
@click.argument("newname", type=str)
def imp(name, newname, pool):
    args = [
            "virsh",
            "vol-create-as",
            pool,
            newname,
            "0",
            "--backing-vol",
            name,
            "--format",
            "qcow2",
            "--backing-vol-format",
            "qcow2",
        ]

    log.info(f"cloning with command {args}")
    subprocess.check_call(args)
    log.info("succeeded")


if __name__ == "__main__":
    imp()
